spring:
  jpa:
      hibernate:
       ddl-auto: update
      show-sql: true
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 730805
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&amp;characterEncoding=UTF-8
#     http传输默认字符集设置
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
